version: '3.8'

services:
  # LOAD BALANCER
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    links:
      - client
      - server
    depends_on:
      - client
      - server
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - '8000:80'

  # CLIENT
  client:
    build: ./client
    container_name: client
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./client/src:/client/src

  # SERVER
  server:
    build: ./server
    container_name: server
    restart: always
    ports:
      - '4040:4040'
    volumes:
      - ./server:/app
    links:
      - mongo
    depends_on:
      - mongo

  # MONGO
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    command: mongod
    expose:
      - 27017
